### ISSUE TITLE
不可行

### ISSUE THREAD

**Issue by dong136279559** [MichleMin/SkeletonView-OC#1]
朋友,这个不可行啊,展示出来的有问题.

**Comment by MichleMin** [comment]
使用方式跟原库相同，我这边使用没有问题，你出现的问题是什么样的呢？集成方式支持Carthage：  github "MichleMin/SkeletonView-OC" "master"

**Comment by dong136279559** [comment]
![7519a651-c9aa-4f48-b3f8-c536ba9c188a](https://user-images.githubusercontent.com/20337504/38462371-ddcee206-3b18-11e8-8aa9-0fb1c42b7e1f.png)
我希望它呈现的样式是红框标注的位置,但是显示有些问题,而且,有的方法,参数为nonnull 不能为空,跟swift中的一些方法有些差异,您能否提供下实例demo呢?不胜感谢....

**Comment by MichleMin** [comment]
朋友，你这个是使用库的方法问题，建议你去下一个官方的demo仔细看看，其实要想在oc项目中使用这个库，只需要将该库下载在本地然后修改它的源码，在你需要调用的类或者方法前面加上@objc关键字，最后将这个库放在git上，使其支持carthage导入即可。
